### ISSUE TITLE
Allow experimenter to specify VM memory and device driver model in gen.py

### ISSUE THREAD

**Issue by edugrasa** [IRATI/demonstrator#10]
Could be options of gen.py script or part the demonstrator .conf file. Defaults could be 128 for memory (or 256? with 128 there are issues running rina-tgen) and 'e1000' for the net device (or maybe 'virtio-net-pci' directly, since it provides better performance?)

**Comment by vmaffione** [comment]
Yes, see the updates. The --memory option was already there.
The --frontend option has been added to choose between e1000 and virtio-net (default)

**Comment by vmaffione** [comment]
128M is the right thing for packing up as many VM as possible, and let simple tests (e.g. ping) to be done. So it makes sense that we keep that as a default. If you want to do performance tests just use the -m option to give more memory.

I guess we can close this!
