### ISSUE TITLE
Be able to specify delay in a link

### ISSUE THREAD

**Issue by edugrasa** [IRATI/demonstrator#16]
Same way bandwidth restrictions are specified (I understand that it could work the same way bandwidth shaping works - via qdiscs?)

Not urgent, but would be handy for the deltaQ experiments.

**Comment by vmaffione** [comment]
It's a good idea, we can go for it. Don't think it can be done with qdisc (it's not traffic shaping or scheduling), but can be done with netem.

**Comment by vmaffione** [comment]
Initial support for delay/loss/duplicate packets emulation is now available.
You can refer to the relative section in the manual. For the time being it is not compatible with the rate limiting.

**Comment by vmaffione** [comment]
The incompatibility issue is not there anymore. You should now be able to use delay/loss/duplicate and/or rate limiting.

**Comment by vmaffione** [comment]
when you have time, please let me know if this works, so that we can close it. An example of netem command is in the gen.conf default file, commented out.
