### ISSUE TITLE
Ability to specify different overlay directories for each VM in the experiment

### ISSUE THREAD

**Issue by edugrasa** [IRATI/demonstrator#19]
This is required in order to pass to the VM specific files required for executing the experiment (notably keys and certificates), which need to have the same file name(s) but different contents in the different machines. This one is a blocker for the ISP security experiment in D6.3: https://wiki.ict-pristine.eu/WP6/d63/d63-demos-network-service-provider.

Proposal: I would specify a "overlay" keyword in the .conf file, with the following syntax:
_overlay <machine_name> <path to dir>_

So, for example

overlay tor1  creds/tor1/
overlay tor2 creds/tor2/
...

These settings would override the --overlay parameter settings in case this option was provided to gen.py.

**Comment by vmaffione** [comment]
I've tried to implement that and updated the documentation.

Can you
- check that it is working for you
- add the demo gen.conf and overlay files in the examples/ and overlays/ directories of the demonstrator repository and issue a pull request, so that anyone can try the demo without further files
  ?

**Comment by edugrasa** [comment]
I don't think it works completely, maybe it's my fault :) 
- I'm trying to overlay a folder which contains the following subfolders: /creds, /creds/ssh2, /creds/tls, and there are actually some files within /creds/ssh2 right now. gen.py complains that the overlay folder is empty (there are no files but there are subfolders), and there is no mention to the overlay folder in the generated up.sh script (in the scp parts of it)
- I tried to specify an overlay folder relative to the folder where gen.py is located but gen.py said it couldn't locate the folder (it only works if I specify the absolute path)

**Comment by vmaffione** [comment]
There was an issue with Python2 (I'm using Python3). Can you try again now?

In my tests, I have the following overlays tree in the demonstrator root directory

```
vmaffione@figaro ~/git/nxw/demonstrator >> tree overlays
overlays
└── a
    ├── creds
    │   ├── ssh2
    │   │   └── file1
    │   └── tls
    │       └── file2
    └── etc
        └── x

5 directories, 3 files

```

And I use the following overlay directive:

```
eth 300 0Mbps a b
[...]
overlay a overlays/a
```

**Comment by edugrasa** [comment]
I don't know what's wrong but it doesn't work for me.. Maybe is my setup, I'll clone the repo again..
But still doesn't find the relative paths and when I provide an absolute paths it doesn't copy the right files..

**Comment by vmaffione** [comment]
Can you please attach your gen.conf? It sounds like an issue with how we use the python libraries.

**Comment by edugrasa** [comment]
eth 110 0Mbps cpe11 ar1
eth 120 0Mbps cpe12 ar1
eth 130 0Mbps cpe13 ar1
eth 210 0Mbps cpe21 ar2
eth 220 0Mbps cpe22 ar2
eth 230 0Mbps cpe23 ar2
eth 310 0Mbps cpe31 ar3
eth 320 0Mbps cpe32 ar3
eth 330 0Mbps cpe33 ar3
eth 100 0Mbps ar1 manpe1
eth 200 0Mbps ar2 manpe1
eth 300 0Mbps ar3 manpe2
eth 410 0Mbps manpe1 manpe2
eth 411 0Mbps manpe1 manpe3
eth 412 0Mbps manpe1 manpe4
eth 420 0Mbps manpe2 manpe3
eth 421 0Mbps manpe2 manpe4
eth 430 0Mbps manpe3 manpe4
eth 510 0Mbps manpe3 ser1
eth 520 0Mbps manpe4 ser2
eth 600 0Mbps ser1 core1
eth 610 0Mbps ser1 core2
eth 620 0Mbps ser2 core1
eth 630 0Mbps ser2 core2
eth 700 0Mbps core1 core2
eth 710 0Mbps core1 core3
eth 720 0Mbps core2 core4
eth 730 0Mbps core3 core4
eth 640 0Mbps core3 edge1
eth 650 0Mbps core4 edge1
eth 660 0Mbps core3 edge2
eth 670 0Mbps core4 edge2
eth 800 0Mbps edge1 isp2
eth 810 0Mbps edge1 isp3
eth 820 0Mbps edge2 isp4
eth 830 0Mbps edge2 isp5

# DIF core

dif core ser1 600 610
dif core ser2 620 630
dif core core1 600 620 700 710
dif core core2 610 630 700 720
dif core core3 640 660 710 730
dif core core4 650 670 720 730
dif core edge1 640 650
dif core edge2 660 670

# DIF access

dif access ar1 100
dif access ar2 200
dif access ar3 300
dif access manpe1 100 200 410 411 412
dif access manpe2 300 410 420 421
dif access manpe3 411 420 430 510
dif access manpe4 412 421 430 520
dif access ser1 510
dif access ser2 520

# DIF service

dif service ar1 access
dif service ar2 access
dif service ar3 access
dif service ser1 access core
dif service ser2 access core
dif service edge1 access core
dif service edge2 access core

# DIF emall1

dif emall1 cpe11 110
dif emall1 cpe12 120
dif emall1 cpe21 210
dif emall1 cpe22 220
dif emall1 cpe31 310
dif emall1 ar1 110 120 service
dif emall1 ar2 210 220 service
dif emall1 ar3 310 service
dif emall1 edge1 service 800
dif emall1 edge2 service 820
dif emall1 isp2 800
dif emall1 isp4 820

# DIF emall2

dif emall2 cpe13 130
dif emall2 cpe23 230
dif emall2 cpe32 320
dif emall2 cpe33 330
dif emall2 ar1 130 service
dif emall2 ar2 230 service
dif emall2 ar3 320 330 service
dif emall2 edge1 service 810
dif emall2 edge2 service 830
dif emall2 isp3 810
dif emall2 isp5 830

#Overlays
overlay ar1 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/ar1
overlay ar2 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/ar2
overlay ar3 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/ar3
overlay core1 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/core
overlay core2 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/core2
overlay core3 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/core3
overlay core4 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/core4
overlay cpe11 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe11
overlay cpe12 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe12
overlay cpe13 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe13
overlay cpe21 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe21
overlay cpe22 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe22
overlay cpe23 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe23
overlay cpe31 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe31
overlay cpe32 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe32
overlay cpe33 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/cpe33
overlay edge1 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/edge1
overlay edge2 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/edge2
overlay isp2 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/isp2
overlay isp3 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/isp3
overlay isp4 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/isp4
overlay isp5 /home/i2cat/edu/demonstrator-isp-sec/overlays/isp-sec/isp5

**Comment by vmaffione** [comment]
ok, so this file does work, right (because of absolute paths)?
And you are saying it does not work with relative paths (e.g. "overlays/expname/node-name")?

**Comment by edugrasa** [comment]
Yeap, and even with the absolute paths the right files are not copied in the machines.. The files in /home/i2cat/edu/demonstrator are copied instead of the files in the specified overlay directory (which is weird because this is the path to another demonstrator copy, not the one that I'm running).. 

Do I have to specify the -overlay option in gen.conf?

**Comment by vmaffione** [comment]
No, you don't have to specify the --overlay option if you don't want to. The --overlay option is to specify the overlay tree that applies to all VMs. In your case I guess you don't need it.

I tried to harden a bit the code to better manage the relative paths. Can you give a try?
Please run gen.py with the current working dir being in the demonstrator repo.
You should able to use relative paths.
I tried with both python2 and python3, and it works nice.

**Comment by edugrasa** [comment]
Finally works :)

The problem was that I had a folder name with the character '-' (isp-sec). All my overlay folders were within _overlays/isp-sec/<node-name>,_ changing it to _overlays/ispsec/<node-name>_ made it work.

**Comment by vmaffione** [comment]
Ah, I see, this was indeed not allowed by the regular expression. Now I allow that.
In any case, always pay attention to the warnings that come out from the demonstrator. If a line is not recognized (because of a syntax/regex mismatch), the demonstrator will tell you. I just did another fix that makes sure you see the warning if there is a syntax problem in the overlay path.

**Comment by edugrasa** [comment]
Great, thanks Vincenzo!

**Comment by vmaffione** [comment]
Maybe you still have to finish to setup the experiment, but when you are ready can you please add the configuration files of your experiments as a Pull Request? In this way we would have a portable experiment, which would be cool!
