### ISSUE TITLE
Be able to specify log level 

### ISSUE THREAD

**Issue by edugrasa** [IRATI/demonstrator#20]
Right now the log level is always DEBUG, would be nice to specify a log level option when calling the gen.py script (DEBUG is fine for the default if option is not provided).

**Comment by vmaffione** [comment]
Right, that's an easy add, pushed in the queue

**Comment by vmaffione** [comment]
Done.
Actually I think the right one is DBG, not DEBUG... check in librina/logs.h

**Comment by vmaffione** [comment]
(just reopen it if it does not work as expected)

**Comment by edugrasa** [comment]
Works nice!
