### ISSUE TITLE
manual enrollment specification

### ISSUE THREAD

**Issue by edugrasa** [IRATI/demonstrator#22]
Not sure how complicated this is, but for some experiments the enrollment algorithms currently available don't always do what you want.. What do you think of adding a new value for the '_-e_' flag option called "_manual_", that would just carry out the enrollments specified in the "conf" file? (if any)

In the conf file we could specify the enrollments like this for example (_enroll dif-name system a sytemb n-1-DIF-name_)
- enroll normal.DIF n1 n2 810

**Comment by vmaffione** [comment]
Yes, I think it's a good idea to support this. Also because if you ask it means that you need it :)
I can do this, it shouldn't be difficult.

**Comment by vmaffione** [comment]
Yes, I think it's a good idea to support this. Also because if you ask it means that you need it :)
I can do this, it shouldn't be difficult.

**Comment by vmaffione** [comment]
Implemented and added the associated documentation. Let me know if that works to you.

**Comment by edugrasa** [comment]
Works like a charm!
